bash neighbor-districts-modified.sh
echo "."
echo "."
echo "Q1: neighbor-districts-modified.sh executed successfully!"
echo "."
echo "."
bash edge-generator.sh
echo "."
echo "."
echo "Q2: edge-generator.sh executed successfully!"
echo "."
echo "."
bash case-generator.sh
echo "."
echo "."
echo "Q3: case-generator.sh executed successfully!"
echo "."
echo "."
bash peaks-generator.sh
echo "."
echo "."
echo "Q4: peaks-generator.sh executed successfully!"
echo "."
echo "."
bash vaccinated-count-generator.sh
echo "."
echo "."
echo "Q5: vaccinated-count-generator.sh executed successfully!"
echo "."
echo "."
bash vaccination-population-ratio-generator.sh
echo "."
echo "."
echo "Q6: vaccination-population-ratio.sh executed successfully!"
echo "."
echo "."
bash vaccine-type-ratio-generator.sh
echo "."
echo "."
echo "Q7: vaccine-type-ratio-generator.sh executed successfully!"
echo "."
echo "."
bash vaccinated-ratio-generator.sh
echo "."
echo "."
echo "Q8: vaccinated-ratio-generator.sh executed successfully!"
echo "."
echo "."
bash complete-vaccination-generator.sh
echo "."
echo "."
echo "Q9: complete-vaccination-generator.sh executed successfully!"
echo "."
echo "."
echo "All output files are generated!"
